### ISSUE TITLE
Add error message when failing to access blockchain

### ISSUE THREAD

**Issue by lander2k2** [qleet/web3-sample-app#9]
Currently, if I point the sample app at an incorrect API endpoint in it's configmap, when I attempt to "Get Balance" the app just hangs and does nothing.  For example:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: web3-sample-app-config
  namespace: sample-app
data:
  RPCENDPOINT: https://api.publicapis.org/entries
```
I suggest we return an error to the user that says something like `could not retrieve info from blockchain using <RPCENDPOINT>`
